// The golden every SDK is checked against, and how the suites get a model.
//
// `Resources/schemer_golden.json` records what the reference harness
// (schemer-training's `predict_for_schema`) returns on the exported graphs,
// once per backend: Core ML on Apple, LiteRT everywhere else. The texts are
// written for the purpose rather than sampled from an eval set, because this
// repository is public and a golden publishes its inputs. Generated by
// schemer-training/tools/release/dump_sdk_golden.py; packages/schemer-node and
// packages/schemer-kotlin read the same file.

import Foundation
import Testing
import TestSupport
@_spi(SchemerBindings) @testable import Schemer

#if !os(WASI)  // bundle resources are not readable under the wasm test harness
struct Golden: Decodable {
    struct FieldSpec: Decodable {
        struct Items: Decodable { let properties: [FieldSpec]? }
        let name: String
        let type: String
        let describe: String?
        let nullable: Bool?
        let values: [String]?
        let min: Double?
        let max: Double?
        let unit: String?
        /// An array of objects: `items.properties`, listed in order.
        let items: Items?

        var field: Field {
            if type == "array", let properties = items?.properties {
                return .objects(name, properties: properties.map(\.field), describe: describe,
                                nullable: nullable)
            }
            return switch type {
            case "number": .number(name, describe: describe, nullable: nullable,
                                   min: min, max: max, unit: unit)
            case "boolean": .boolean(name, describe: describe, nullable: nullable)
            case "datetime": .datetime(name, describe: describe, nullable: nullable)
            case "array": .array(name, describe: describe, nullable: nullable)
            case "label": .label(name, values: values ?? [], describe: describe, nullable: nullable)
            default: .string(name, describe: describe, nullable: nullable)
            }
        }
    }

    /// A value as JSON carries it.
    enum Answer: Decodable, Equatable, CustomStringConvertible {
        case null, string(String), number(Double), boolean(Bool), array([String])
        /// An array of objects, each holding only the properties it states.
        case objects([[String: Answer]])

        init(from decoder: Decoder) throws {
            let c = try decoder.singleValueContainer()
            if c.decodeNil() { self = .null }
            else if let v = try? c.decode(Bool.self) { self = .boolean(v) }
            else if let v = try? c.decode(Double.self) { self = .number(v) }
            else if let v = try? c.decode(String.self) { self = .string(v) }
            else if let v = try? c.decode([String].self) { self = .array(v) }
            else { self = .objects(try c.decode([[String: Answer]].self)) }
        }

        init(_ value: Value) {
            switch value {
            case .null: self = .null
            case .string(let s), .datetime(let s), .label(let s): self = .string(s)
            case .number(let d): self = .number(d)
            case .boolean(let b): self = .boolean(b)
            case .array(let xs): self = .array(xs)
            case .objects(let items):
                self = .objects(items.map { item in
                    Dictionary(uniqueKeysWithValues: item.entries.map { ($0.name, Answer($0.value)) })
                })
            }
        }

        /// The reference writes "" for an absent non-nullable string, which is
        /// the same answer as null.
        func matches(_ other: Answer) -> Bool {
            switch (self, other) {
            case (.number(let a), .number(let b)): return abs(a - b) < 1e-6
            case (.string(""), .null), (.null, .string("")): return true
            // `[]` decodes as an empty string array; for an objects field it
            // is the same answer as no items.
            case (.objects(let a), .array(let b)), (.array(let b), .objects(let a)):
                return a.isEmpty && b.isEmpty
            case (.objects(let a), .objects(let b)):
                return a.count == b.count && zip(a, b).allSatisfy { x, y in
                    x.keys.sorted() == y.keys.sorted() && x.allSatisfy { k, v in v.matches(y[k]!) }
                }
            default: return self == other
            }
        }

        var description: String {
            switch self {
            case .null: "null"
            case .string(let s): "\"\(s)\""
            case .number(let d): "\(d)"
            case .boolean(let b): "\(b)"
            case .array(let xs): "\(xs)"
            case .objects(let items): "\(items.map { $0.mapValues(\.description) })"
            }
        }
    }

    struct Case: Decodable {
        let id: String
        let lang: String
        /// `YYYY-MM-DD`, passed as `now`.
        let now: String
        let text: String
        let schema: [FieldSpec]
        let expected: [String: [String: Answer]]

        var schemaValue: Schema { Schema(schema.map(\.field)) }
        var date: Date { Schemer.date(fromAnchor: "today=\(now)")! }

        /// The answers for the backend this platform runs.
        var answers: [String: Answer] { expected[Golden.backend]! }
    }

    let revision: String
    let cases: [Case]

    /// Core ML on Apple, LiteRT everywhere else: the same split as the catalog.
    static var backend: String {
        #if canImport(CoreML)
        "coreml"
        #else
        "litert"
        #endif
    }

    /// How many of `fields` may differ from the golden here.
    ///
    /// The golden was made on an M1 (the Neural Engine for Core ML, NEON
    /// kernels for LiteRT), and every ARM64 host measured (macOS, Android,
    /// Linux, Node) matches it on every field; 2% covers another Neural Engine
    /// generation. The Simulator runs Core ML on the CPU in other arithmetic
    /// (1 field of 115 differs), so 5%. On x86_64 the LiteRT files'
    /// dynamic-range int8 runs on different kernels, which quantize the
    /// activations at run time and round a field that sits on a decision
    /// boundary the other way: 5 of 115 on a Linux runner, 8 on the x86_64
    /// Android emulator, so 10% there. Every disagreement is printed.
    static func allowedDisagreements(of fields: Int) -> Int {
        #if targetEnvironment(simulator)
        let share = 0.05
        #elseif arch(x86_64)
        let share = 0.10
        #else
        let share = 0.02
        #endif
        return Int((Double(fields) * share).rounded(.up))
    }

    static func load() throws -> Golden {
        let url = try #require(Bundle.module.url(forResource: "schemer_golden", withExtension: "json"))
        return try JSONDecoder().decode(Golden.self, from: Data(contentsOf: url))
    }
}

/// The model the model-backed suites run.
///
/// `SCHEMER_MODEL_DIR` points at a local export laid out as the Hub revision is
/// (the directory `schemer-training/tools/release/stage_hub.py` writes), for
/// testing a revision before it is published. Without it the suites resolve the
/// pinned revision like every other model's.
enum SchemerFixture {
    static var directory: String? { ProcessInfo.processInfo.environment["SCHEMER_MODEL_DIR"] }

    /// Model-backed tests run where every model's do, and also wherever a
    /// local model directory was named: that is a deliberate choice to pay for
    /// the model, so it opts an iOS Simulator run in too (the simulator reads
    /// host paths).
    static var runs: Bool { runsModelBackedTests || directory != nil }

    private static let shared = Task<Schemer, Error> {
        let schemer = Schemer(directory: directory)
        try await schemer.waitUntilLoaded()
        return schemer
    }

    /// One loaded extractor for the whole target: the encoder alone is 109 MB,
    /// and the suites' cost is otherwise dominated by loading it again.
    static func schemer() async throws -> Schemer { try await shared.value }

    /// The directory holding the resolved model files, for tests that read a
    /// sidecar directly.
    static func files() async throws -> URL {
        if let directory { return URL(fileURLWithPath: directory) }
        return URL(fileURLWithPath: try await SchemerModel.resolve().rootPath)
    }
}
#endif
