#!/usr/bin/env bash
# Build the two Google Tensor (Pixel TPU) vendor libraries LiteRT needs for its
# NPU path, from the LiteRT source tree, with the plain NDK - no bazel, no
# protobuf. Produces, for arm64-v8a:
#
#   libLiteRtDispatch_GoogleTensor.so        the runtime dispatch library
#   libLiteRtCompilerPlugin_google_tensor.so the on-device (JIT) compiler plugin
#
# These are what a session sets DAL_NPU_LIBRARY_DIR to (the shim passes the dir
# as DispatchLibraryDir + CompilerPluginLibraryDir; see Sources/CLiteRt/shim.c).
#
# STATUS (2026-09, Pixel 11 / Tensor G6, LiteRT 2.2.0): both libraries build
# and load, the on-device EdgeTPU compiler runs, and then the compile is
# refused by vendor.google.edgetpu_app_service with error 16, "not in the
# EdgeTPU allowed list" - a per-package allowlist inside a Google-signed
# service, not something these libraries or our code can satisfy. The NNAPI
# path (Tools/npu/decprobe.c) reaches the SAME TPU with NO such gate, so that
# is the route to pursue; this recipe is kept because it is the only public
# way to produce these libraries and because the allowlist may open.
#
# Pins to the LiteRT tag matching the runtime we ship (Vendor/litert), so the
# dispatch library and libLiteRt.so agree on their internal ABI. A mismatch
# aborts inside libLiteRt.so at delegate-kernel init (seen with a 2.1.6
# dispatch library against a 2.2.0 runtime).
#
# Prereqs: an Android NDK (r27+), and git. Everything else (abseil, re2, the
# LiteRT sources) is fetched here. Run from anywhere; writes to a work dir.
set -euo pipefail

LITERT_TAG="${LITERT_TAG:-v2.2.0}"
NDK="${ANDROID_NDK_HOME:?set ANDROID_NDK_HOME to an r27+ NDK}"
API="${DAL_ANDROID_API:-26}"
WORK="${DAL_NPU_WORK:-$HOME/.cache/desert-ant/npu-build}"
OUT="${1:-$(pwd)/npu-libs}"

host="$(uname -s | tr '[:upper:]' '[:lower:]')-x86_64"
CXX="$NDK/toolchains/llvm/prebuilt/$host/bin/aarch64-linux-android$API-clang++"
[ -x "$CXX" ] || { echo "no clang++ at $CXX" >&2; exit 1; }

mkdir -p "$WORK" "$OUT"
cd "$WORK"

# --- sources ---------------------------------------------------------------
# abseil and re2 are compiled from source (the plugin links a handful of each);
# a shallow clone of each at a recent release is enough.
[ -d abseil-cpp ] || git clone --depth 1 https://github.com/abseil/abseil-cpp
[ -d re2 ] || git clone --depth 1 https://github.com/google/re2
if [ ! -d litert-src ]; then
    git clone --depth 1 --filter=blob:none --sparse https://github.com/google-ai-edge/LiteRT litert-src
    ( cd litert-src && git sparse-checkout set \
        litert/c litert/cc litert/core litert/vendors litert/compiler \
        litert/build_common tflite/c tflite/core/c tflite/converter/core/c )
fi
cd litert-src
git fetch --depth 1 origin tag "$LITERT_TAG"
git checkout "$LITERT_TAG"

# build_config.h is generated by CMake from a template; the checked-in
# gpu_npu variant is the one we want (GPU and NPU both enabled).
cp litert/build_common/config/build_config_gpu_npu.h litert/build_common/build_config.h

# --- protobuf stand-ins ----------------------------------------------------
# The plugin's two .proto messages are pulled in only through generated
# headers. Rather than run protoc and link libprotobuf for two tiny messages,
# hand-roll the proto3 wire format. Kept in this repo (see *.pb.h next to this
# script) and copied into place; a schema change in a future LiteRT tag means
# regenerating these by hand (diff the .proto between tags - the field numbers
# are what matter).
cp "$(dirname "$0")"/edgetpu_compiler_options.pb.h \
   litert/vendors/google_tensor/edgetpu_compiler_options.pb.h
cp "$(dirname "$0")"/google_tensor_options.pb.h \
   litert/vendors/google_tensor/compiler/google_tensor_options.pb.h

# text_format.h is included unconditionally by compiler_plugin.cc but only used
# under !defined(__ANDROID__); a one-line stub satisfies the include.
mkdir -p "$WORK/pbstub/google/protobuf"
cat > "$WORK/pbstub/google/protobuf/text_format.h" <<'STUB'
#ifndef GOOGLE_PROTOBUF_TEXT_FORMAT_STUB_H_
#define GOOGLE_PROTOBUF_TEXT_FORMAT_STUB_H_
namespace google { namespace protobuf { class TextFormat; } }
#endif
STUB

# adapter_odc.cc hardcodes an absolute /vendor path for the EdgeTPU runtime; an
# app process may only reach it through the linker's public-library namespace,
# so load it by soname instead (the app declares it with uses-native-library).
perl -0pi -e 's{constexpr const char\* kLiteRtLibPath = "/vendor/lib64/libedgetpu_litert.so";}{constexpr const char* kLiteRtLibPath = "libedgetpu_litert.so";}' \
    litert/vendors/google_tensor/adapter_odc.cc

# --- compile ---------------------------------------------------------------
b="$WORK/obj"; mkdir -p "$b/absl" "$b/re2" "$b/plugin"
inc=(-I. -I"$WORK/abseil-cpp" -I"$WORK/re2" -I"$WORK/pbstub")
cflags=(-std=c++17 -Os -fPIC -fno-exceptions -ffunction-sections -fdata-sections)

echo "compiling abseil (subset) ..."
absl_globs=(
    absl/base/*.cc absl/base/internal/*.cc absl/strings/*.cc
    absl/strings/internal/*.cc absl/strings/internal/str_format/*.cc
    absl/container/internal/*.cc absl/hash/internal/*.cc absl/numeric/*.cc
    absl/debugging/*.cc absl/debugging/internal/*.cc absl/time/*.cc
    absl/time/internal/cctz/src/*.cc absl/synchronization/*.cc
    absl/synchronization/internal/*.cc absl/crc/*.cc absl/crc/internal/*.cc
    absl/profiling/internal/*.cc absl/log/*.cc absl/log/internal/*.cc
    absl/flags/*.cc absl/flags/internal/*.cc
)
( cd "$WORK/abseil-cpp"
  for f in ${absl_globs[@]}; do
      case "$f" in *_test*|*_benchmark*|*test_util*|*mock_*|*_testonly*) continue;; esac
      [ -f "$f" ] || continue
      o="$b/absl/$(echo "$f" | tr '/' '_').o"
      "$CXX" -c "$f" -I. "${cflags[@]}" -o "$o" 2>/dev/null || true
  done )

echo "compiling re2 ..."
( cd "$WORK/re2"
  for f in re2/*.cc util/*.cc; do
      case "$f" in *test*|*benchmark*|*fuzz*) continue;; esac
      "$CXX" -c "$f" -I. -I"$WORK/abseil-cpp" "${cflags[@]}" \
          -o "$b/re2/$(echo "$f" | tr '/' '_').o" 2>/dev/null || true
  done )

echo "compiling litert shared helpers ..."
helpers=(
    litert/c/options/litert_google_tensor_options.cc
    litert/core/util/tensor_type_util.cc
    litert/core/litert_toml_parser.cc
    litert/c/internal/litert_logging_helper_with_runtime_context.cc
    litert/c/internal/litert_logging_helper_with_compiler_context.cc
)
for f in "${helpers[@]}"; do
    "$CXX" -c "$f" "${inc[@]}" "${cflags[@]}" -o "$b/$(basename "$f" .cc).o"
done

echo "compiling dispatch library sources ..."
dispatch=(
    dispatch_api dispatch_api_config dispatch_api_utils
    litert_dispatch_device_context litert_dispatch_graph
    litert_dispatch_invocation_context sb_api_late_binding
)
for s in "${dispatch[@]}"; do
    "$CXX" -c "litert/vendors/google_tensor/dispatch/$s.cc" "${inc[@]}" "${cflags[@]}" -o "$b/$s.o"
done

echo "compiling compiler plugin sources ..."
for f in litert/vendors/google_tensor/compiler/compiler_plugin.cc \
         litert/vendors/google_tensor/adapter_odc.cc; do
    "$CXX" -c "$f" "${inc[@]}" "${cflags[@]}" -o "$b/plugin/$(basename "$f" .cc).o"
done

# --- link ------------------------------------------------------------------
# -static-libstdc++: the device has no libc++_shared.so on the app's linker
# path, so bundle the C++ runtime into each library. libLiteRt is linked
# against so the LiteRt* symbols resolve to the shipping runtime at load.
LLD=(-Wl,--gc-sections -L"$(dirname "$0")/../../Vendor/litert/lib/android-aarch64"
     -lLiteRt -llog -landroid -Wl,--no-undefined)
litert_lib="$(dirname "$0")/../../Vendor/litert/lib/android-aarch64/libLiteRt.so"
[ -f "$litert_lib" ] || { echo "need Vendor/litert/lib/android-aarch64/libLiteRt.so (run build:android-natives once)" >&2; exit 1; }

echo "linking libLiteRtDispatch_GoogleTensor.so ..."
"$CXX" -shared -static-libstdc++ -o "$OUT/libLiteRtDispatch_GoogleTensor.so" \
    "$b"/dispatch_api.o "$b"/dispatch_api_config.o "$b"/dispatch_api_utils.o \
    "$b"/litert_dispatch_device_context.o "$b"/litert_dispatch_graph.o \
    "$b"/litert_dispatch_invocation_context.o "$b"/sb_api_late_binding.o \
    "$b"/litert_google_tensor_options.o "$b"/litert_toml_parser.o \
    "$b"/tensor_type_util.o "$b"/litert_logging_helper_with_runtime_context.o \
    "$b"/absl/*.o -Wl,-soname=libLiteRtDispatch_GoogleTensor.so "${LLD[@]}"

echo "linking libLiteRtCompilerPlugin_google_tensor.so ..."
"$CXX" -shared -static-libstdc++ -o "$OUT/libLiteRtCompilerPlugin_google_tensor.so" \
    "$b"/plugin/compiler_plugin.o "$b"/plugin/adapter_odc.o \
    "$b"/litert_logging_helper_with_compiler_context.o \
    "$b"/litert_google_tensor_options.o "$b"/litert_toml_parser.o "$b"/tensor_type_util.o \
    "$b"/absl/*.o "$b"/re2/*.o \
    -Wl,-soname=libLiteRtCompilerPlugin_google_tensor.so "${LLD[@]}"

echo "done:"
ls -la "$OUT"/libLiteRt*.so
